# Even Fibonacci Numbers

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

import time

t1 = time.time()

fib = [1, 2]

while fib[-1] < 4e6:
    fib.append(fib[-1] + fib[-2])

# Remove the last element (greater than four million)
fib.pop()

S = 0

# Sum of even-valued terms
for f in fib:
    if f%2 == 0:
        S += f


t2 = time.time()
dt = t2-t1

print(f"Elapsed time: {dt:e} s")
print()

print(S)
